export const events = [
  {
    image: '/images/event1.png',
    title: 'Next.js Conf 2026',
    slug: 'nextjs-conf-2026',
    location: 'San Francisco, CA',
    date: 'October 24, 2026',
    time: '9:00 AM PST',
  },
  {
    image: '/images/event2.png',
    title: 'React Summit',
    slug: 'react-summit-2026',
    location: 'Amsterdam, Netherlands',
    date: 'June 14, 2026',
    time: '8:30 AM CET',
  },
  {
    image: '/images/event3.png',
    title: 'Vercel Ship',
    slug: 'vercel-ship-2026',
    location: 'New York, NY',
    date: 'May 10, 2026',
    time: '10:00 AM EST',
  },
  {
    image: '/images/event4.png',
    title: 'React Native Connection',
    slug: 'react-native-connection-2026',
    location: 'Paris, France',
    date: 'April 23, 2026',
    time: '9:00 AM CET',
  },
  {
    image: '/images/event5.png',
    title: 'Tailwind Connect',
    slug: 'tailwind-connect-2026',
    location: 'Remote',
    date: 'July 15, 2026',
    time: '10:00 AM PST',
  },
  {
    image: '/images/event6.png',
    title: 'JSWorld Conference',
    slug: 'jsworld-conference-2026',
    location: 'Amsterdam, Netherlands',
    date: 'Feb 28, 2026',
    time: '9:00 AM CET',
  },
];
